name: Lint on main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: ESLint no branch main
    runs-on: ubuntu-latest
    env:
      PRODUCTION_ENVIRONMENT: ${{ secrets.PRODUCTION_ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - run: npm ci
      - name: Rodar ESLint
        run: npx eslint --ext .ts .